### ISSUE TITLE
Debugger name button width / ensuring the whole widget has static width

### ISSUE THREAD

**Issue by Spown** [fabiospampinato/vscode-statusbar-debugger#8]
As per #4 

![](https://drive.google.com/uc?id=1VCEou2FVIOU9zrZ716gOto4rrsIG8ZNI)

Can you make the button assume the longest debugger name (i.e. in case of compound debuggers, make it's width static as long as no new debuggers are added or present ones stopped), so that the following control buttons wouldn't jump left and right?

Thank you.

**Comment by fabiospampinato** [comment]
VSC still doesn't expose enough information about compound debugging for implementing this (https://github.com/Microsoft/vscode/issues/30810).

You can, however, put `"statusbarDebugger.template": "$(bug)"` in your settings in order to hide the name entirely, or, using [this extension](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css), you can assign a fixed width to that button.

**Comment by Spown** [comment]
``Custom CSS and JS Loader`` introduces too much enthropy. Can you maybe add a setting? something like ``"statusbarDebugger.mainButtonMinWidth": number``?

**Comment by fabiospampinato** [comment]
VSC provides no API for doing this thing, the only way I could implement it would be by basically doing what  "Custom CSS and JS Loader" does, but I don't see the point in that.

Another option you could try is to rename your configurations, adding some non-breakable whitespace characters at the end until they all occupy the same width, maybe that could work.

**Comment by Spown** [comment]
>Another option you could try is to rename your configurations, adding some non-breakable whitespace characters at the end until they all occupy the same width, maybe that could work.

The font used there isn't monospace, so it'll be jumping anyway. Oh well, thanks anyway.
